// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RxCloseAPI.Persistence;

#nullable disable

namespace RxCloseAPI.Migrations
{
    [DbContext(typeof(RxCloseDbContext))]
    [Migration("20250610120000_AddSellerInfoToProducts")]
    partial class AddSellerInfoToProducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            // Entity configurations would go here - this is simplified
            // The actual content would match the current model snapshot
#pragma warning restore 612, 618
        }
    }
} 